### ISSUE TITLE
Annotating signal peptides

### ISSUE THREAD

**Issue by TomSmithCGAT** [lgatto/pRolocGUI#101]
For 'aggar', it would be really useful to annotate the peptides according to whether they are before/after/overlapping a signal peptide cleavage site. 

I've spoke with @lmsimp about this and she's happy to add this annotation to the underlying data if I can include code here to query the uniprot API for signal peptide coordinates and annotate peptides accordingly.

**Comment by lmsimp** [comment]
@TomSmithCGAT Actually thinking it would be best for me to create a standalone copy the aggregate app for a dedicated dataset and then see if this is something we wish to add to the general app. I will create a new repo.

**Comment by TomSmithCGAT** [comment]
Yep. Sounds good. I've just realised that positional information for each peptide is not necessarily included in the peptide-level datasets. Do you mind if I work from an unpublished dataset as a test case to start with and we can work out how/whether to integrate this more generally?

**Comment by lmsimp** [comment]
No this is fine with me. Closing and opening in shiny apps. Thanks
