### ISSUE TITLE
allow list of matrices as input

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRolocGUI#114]
Compare app does not currently allow users to pass a list of matrices (e.g. as generated from a t-SNE projection) as input. Only an `MSnSetList` is accepted.

**Comment by lgatto** [comment]
Yes, that's the point of an `MSnSetList`. If you want to change that to use general lists, I would suggest to drop `MSnSetList` objects altogether and I would deprecate the class from `MSnbase`.

**Comment by lmsimp** [comment]
I've been wondering about whether `MSnSetList` is no longer needed for this and several related issues. In `pRoloc`

**Comment by lmsimp** [comment]
So it seems I was a bit eager to open this issue! This does work, I hadn't passed my `methargs` as a `list`. This wasn't obvious so I will add a more informative error message. 

Currently, we do allow a list of pre-defined matrices (of length 2) to be passed to the compare app but `method` must be `none` and `methargs` must be specified as a list of `MSnSetList` of length 2. Similar, to what is implemented in `plot2D` e.g.

```
library(pRolocdata)
library(pRolocGUI)
data("hyperLOPIT2015ms3r1")
data("hyperLOPIT2015ms3r2")

xx <- MSnSetList(list(hyperLOPIT2015ms3r1, hyperLOPIT2015ms3r2))

pcas1 <- plot2D(hyperLOPIT2015ms3r1, plot = FALSE)
pcas2 <- plot2D(hyperLOPIT2015ms3r2, plot = FALSE)

pRolocVis(list(pcas1, pcas2), app = "compare", method = "none", methargs = list(xx), fcol = "markers")
```

However, this aside, I've also been wondering about whether `MSnSetList` is no longer needed for several related issues. Let's discuss later.

**Comment by lmsimp** [comment]
Closing this for now but we can re-open or open a new issue to discuss `MSnSetLists`
