### ISSUE TITLE
pRolocVis fails for fcol = NULL

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRolocGUI#81]
Chatting with Konstantin realised the above does not work:

``` r
library(pRolocdata)
library(pRolocGUI)
data(hyperLOPIT2015)
pRolocVis(hyperLOPIT2015, fcol = NULL)
```

**Comment by lmsimp** [comment]
Some people do not have markers but wish to use `pRolocVis` to search their data. If no markers are loaded, the select menu will be empty. This may break the code? Will need to try. Or perhaps we just do not generate that input menu in the GUI.

**Comment by lgatto** [comment]
> Chatting with Konstantin realised the above does not work:

Was it supposed to work? The documentation doesn't say anything about `NULL`. But I agree it should. Also, I get 
```r
> fData(hyperLOPIT2015)$markers <- "unknown"
> pRolocVis(hyperLOPIT2015)
Error in apply(pmarkers, 2, sum, na.rm = TRUE) : 
  dim(X) must have a positive length
Error in pRolocVis_pca(object, fcol = fcol, ...) : 
  object 'idDT' not found
```
I think that once the above works, we would just need to set a marker column to `"unknown"` when `fcol = NULL`.

**Comment by lmsimp** [comment]
Yes, good idea.

**Comment by lmsimp** [comment]
This is not straightforward to implement. We would want to change the shiny layout and remove the selection box in this scenario as there is nothing to select.

**Comment by lgatto** [comment]
@lmsimp - this should be fixed in `pRolocVis_pca`. Could you have a look and let me know if we should implement something similar for the other apps.

**Comment by lgatto** [comment]
Also, I think we should set the default `fcol` to be `"markers"` in `pRolocVis`. This would be consistent with the general behaviour in `pRoloc`, and would make some of the code simpler. But would prefer to check/chat with @lmsimp  before doing that.

**Comment by lmsimp** [comment]
I agree the default should be `"markers"` for `pRolocVis_pca` but for the other apps, this would be tricky.

**Comment by lgatto** [comment]
Currently, the default is also set to `"markers"` for the `classify` app, and there's not default for the `compare` app. I think this could be harmonised and clarified in the docs. Let's discuss and fix this when we are in maths.
